// SPDX-License-Identifier: FSL-1.1-MIT

// Command notices writes THIRD_PARTY_NOTICES.md: the full licence texts and
// copyrights for every third-party component Runbooks distributes — the Go
// modules linked into the shipped binary, the vendored browser JS, and the
// self-hosted fonts.
//
// Output is deterministic, so it can be regenerated and committed: run
// `mise run notices` after a dependency change, and CI fails if the committed
// file drifts. Run from the repository root.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const outputPath = "THIRD_PARTY_NOTICES.md"

// mainModule is the module under audit; its own licence is LICENSE, not a
// third-party notice.
const mainModule = "runbooks"

// headerFormat opens the file with the Runbooks version the notices were
// generated for. The committed file uses the default `dev`; the container build
// regenerates it with the release tag, so a shipped notices file names its own
// version. Backticks are concatenated in so the surrounding literal can stay a
// raw string.
const headerFormat = `# Third-party notices

Runbooks version: %s

Runbooks bundles the third-party components below. Each remains under its own
licence, reproduced here with its copyright. Inventory and classification:
` + "`DEPENDENCIES.md`" + `; licence posture: ` + "`NOTICE`" + `.

Generated by ` + "`mise run notices -version <version>`" + ` — do not edit by hand.
`

type module struct {
	Path    string
	Version string
	Dir     string
}

func main() {
	version := flag.String("version", "dev", "Runbooks version to stamp into the generated header")
	flag.Parse()
	if err := run(*version); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run(version string) error {
	mods, err := distributedModules()
	if err != nil {
		return err
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, headerFormat, version)
	if err := writeModules(&b, mods); err != nil {
		return err
	}
	if err := writeVendors(&b); err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, b.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d modules)\n", outputPath, len(mods))
	return nil
}

// distributedModules returns the third-party modules linked into the binary,
// resolved to their source directories in the module cache.
func distributedModules() ([]module, error) {
	deps, err := goList("-deps", "-f", "{{with .Module}}{{.Path}}{{end}}", ".")
	if err != nil {
		return nil, err
	}
	linked := make(map[string]bool)
	for _, line := range strings.Split(deps, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			linked[line] = true
		}
	}

	all, err := goList("-m", "-f", "{{.Path}}|{{.Version}}|{{.Dir}}", "all")
	if err != nil {
		return nil, err
	}
	var mods []module
	for _, line := range strings.Split(all, "\n") {
		parts := strings.Split(line, "|")
		if len(parts) != 3 {
			continue
		}
		m := module{Path: parts[0], Version: parts[1], Dir: parts[2]}
		if m.Path == mainModule || !linked[m.Path] {
			continue
		}
		if m.Dir == "" {
			return nil, fmt.Errorf("module %s has no source directory; run `go mod download` first", m.Path)
		}
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })
	return mods, nil
}

func goList(args ...string) (string, error) {
	cmd := exec.Command("go", append([]string{"list"}, args...)...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("go list %s: %v: %s", strings.Join(args, " "), err, strings.TrimSpace(stderr.String()))
	}
	return stdout.String(), nil
}

func writeModules(b *bytes.Buffer, mods []module) error {
	fmt.Fprint(b, "\n## Distributed Go modules\n")
	for _, m := range mods {
		files, err := licenceFiles(m.Dir)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			return fmt.Errorf("no licence file found for %s@%s", m.Path, m.Version)
		}
		body, err := os.ReadFile(files[0])
		if err != nil {
			return err
		}
		spdx := classify(string(body))
		fmt.Fprintf(b, "\n### %s %s — %s\n", m.Path, m.Version, spdx)
		for _, f := range files {
			text, err := os.ReadFile(f)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "\n```\n%s\n```\n", strings.TrimRight(string(text), "\n"))
		}
	}
	return nil
}

// writeVendors emits the browser JS, the vendored icons and the fonts. These
// carry no Go module metadata, so their licence texts are checked into the tree
// beside the assets.
func writeVendors(b *bytes.Buffer) error {
	fmt.Fprint(b, "\n## Vendored browser JS\n")
	js := []struct{ name, file string }{
		{"highlight.js 11.11.1 — BSD-3-Clause", "public/js/vendor/highlight.LICENSE"},
		{"marked 15.0.12 — MIT", "public/js/vendor/marked.LICENSE"},
		{"DOMPurify 3.2.4 — Apache-2.0 (elected)", "public/js/vendor/purify.LICENSE"},
		{"JSZip 3.10.1 — MIT (elected)", "public/js/vendor/jszip.LICENSE"},
		{"pako (bundled by JSZip) — MIT", "public/js/vendor/pako.LICENSE"},
	}
	for _, e := range js {
		if err := writeBlock(b, "### "+e.name, e.file); err != nil {
			return err
		}
	}

	fmt.Fprint(b, "\n## Vendored icons\n")
	if err := writeBlock(b, "### Lucide 1.49.0 (icon subset) — ISC", "public/js/vendor/lucide.LICENSE"); err != nil {
		return err
	}

	fmt.Fprint(b, "\n## Fonts\n")
	fmt.Fprint(b, "\nBoth self-hosted fonts are licensed under the SIL Open Font License 1.1,\nreproduced here and shipped alongside them at `public/fonts/OFL.txt`.\n")
	return writeBlock(b, "", "public/fonts/OFL.txt")
}

func writeBlock(b *bytes.Buffer, heading, path string) error {
	text, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if heading != "" {
		fmt.Fprintf(b, "\n%s\n", heading)
	}
	fmt.Fprintf(b, "\n```\n%s\n```\n", strings.TrimRight(string(text), "\n"))
	return nil
}

// licenceFiles returns the licence-like files at the top level of dir, sorted
// so the output is stable.
func licenceFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := strings.ToUpper(e.Name())
		if strings.HasPrefix(name, "LICENSE") || strings.HasPrefix(name, "LICENCE") || strings.HasPrefix(name, "COPYING") {
			files = append(files, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(files)
	return files, nil
}

// classify guesses the SPDX id from the licence text. It is a label, not a
// legal determination — the full text follows it.
func classify(text string) string {
	switch {
	case strings.Contains(text, "Apache License"):
		return "Apache-2.0"
	case strings.Contains(text, "Permission is hereby granted, free of charge"):
		return "MIT"
	case strings.Contains(text, "Permission to use, copy, modify, and/or distribute this software"):
		return "ISC"
	case strings.Contains(text, "Redistribution and use in source and binary forms"):
		if strings.Contains(text, "Neither the name") {
			return "BSD-3-Clause"
		}
		return "BSD-2-Clause"
	case strings.Contains(text, "Mozilla Public License"):
		return "MPL-2.0"
	default:
		return "UNKNOWN"
	}
}
