CREATE TABLE IF NOT EXISTS auth_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at             BIGINT NOT NULL,
    actor_user_id  TEXT,
    action         TEXT NOT NULL,
    target_user_id TEXT,
    ip             TEXT,
    user_agent     TEXT
);
